FROM arm32v7/python:3
RUN pip install --upgrade pip
RUN pip install jupyter
RUN pip install pymysql
RUN pip install pymongo
RUN pip install requests
RUN pip install bs4
RUN pip install pandas
RUN pip install plotly
RUN pip install tqdm
RUN pip install matplotlib