FROM arm32v7/python:3.9.2
RUN pip install jupyter==1.0.0
RUN pip install pandas==1.5.3
RUN pip install pymongo==3.13.0
RUN pip install requests
RUN pip install bs4
RUN pip install plotly
RUN pip install tqdm
RUN pip install matplotlib
RUN pip install pymysql
